language: ruby
rvm:
  - 2.7.6

sudo: false

cache:
  - bundler

branches:
  only:
    - master

before_install:
  - gem update --system

addons:
  code_climate:
    repo_token: 70bb855d43fd2084977765ba11cac1df593df4bc4085fcb9bf39a2d321a20cde
